def loop  # uma função em ruby
  
  # instrução da função 
   
end

def teste (*argers)
  #return 1 if count == 2 # então o return funciona como break 
   #1 + 5 - 3 + (6 * 3)
    
   rescue Exception => e
    puts e.message
end

a = teste 1,2,3,4,5,6,7,8,9,10

puts a